import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Button, Card, Col, DatePicker, Empty, message, Popconfirm, Progress, Row, Skeleton, Space, Statistic, Tag, Typography } from 'antd';
import { AppstoreAddOutlined, CalendarOutlined, CheckCircleOutlined, DeleteOutlined, EditOutlined, PlusOutlined, SafetyOutlined, WalletOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { useOutletContext } from 'react-router-dom';
import api from '../api';
import { HeadNavbar } from '../components';
import DailyGuidedTour from '../components/DailyGuidedTour';
import DailyTransactionTable from '../components/DailyTransactionTable';
import { BudgetActualChart, CategoryExpenseChart, SpendingTrendChart } from '../components/DailyCharts';
import { DailyAllocationForm, DailyBudgetForm, DailyExpenseForm, DailyTopUpForm } from '../components/DailyForms';
import { apiMessage, budgetStatus, rupiah, safeNumber } from '../features/daily';
import { getSessionUser } from '../authSession';
import '../features/daily.css';

const current=dayjs();
const initialFilters={search:'',category_id:'',dates:[],sort:'newest',page:1,page_size:10};
const summaryCards=[['balance','Daily Balance',<WalletOutlined key="balance-icon"/>],['available_balance','Saldo Daily Tersedia',<AppstoreAddOutlined key="available-icon"/>],['budget','Terbagi Bulan Ini',<CalendarOutlined key="budget-icon"/>],['expenses','Pengeluaran Bulan Ini',<WalletOutlined key="expense-icon"/>],['remaining_budget','Sisa Alokasi Bulanan',<SafetyOutlined key="remaining-icon"/>],['average_daily_spending','Average Daily Spending',<CalendarOutlined key="average-icon"/>]];
const usageDate=value=>value?new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`)):'Belum ada pemakaian';

export default function Daily(){
  const canManage=getSessionUser()?.role==='admin';
  const {refreshHeader} = useOutletContext()||{};
  const [month,setMonth]=useState(current.startOf('month')); const [overview,setOverview]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [rows,setRows]=useState([]); const [tableLoading,setTableLoading]=useState(true); const [pagination,setPagination]=useState({page:1,page_size:10,total:0}); const [filters,setFilters]=useState(initialFilters);
  const [topUpOpen,setTopUpOpen]=useState(false); const [allocationOpen,setAllocationOpen]=useState(false); const [expenseOpen,setExpenseOpen]=useState(false); const [expenseCategoryId,setExpenseCategoryId]=useState(null); const [editing,setEditing]=useState(null); const [budgetCategory,setBudgetCategory]=useState(null); const [saving,setSaving]=useState(false);
  const overviewRequest=useRef(0); const tableRequest=useRef(0); const saveInFlight=useRef(false); const period=useMemo(()=>({year:month.year(),month:month.month()+1}),[month]); const periodKey=month.format('YYYY-MM'); const periodLabel=month.format('MMMM YYYY');
  const categories=useMemo(()=>overview?.categories||[],[overview]); const summary=overview?.summary||{};
  const loadOverview=useCallback(async()=>{const request=++overviewRequest.current;setLoading(true);setError('');try{const response=await api.get('/daily/overview',{params:period});if(request===overviewRequest.current)setOverview(response.data.data);}catch(error){if(request===overviewRequest.current){setError(apiMessage(error));setOverview(null);}}finally{if(request===overviewRequest.current)setLoading(false);}},[period]);
  const loadTransactions=useCallback(async()=>{const request=++tableRequest.current;setTableLoading(true);try{const params={...period,page:filters.page,page_size:filters.page_size,sort:filters.sort};if(filters.search.trim())params.search=filters.search.trim();if(filters.category_id)params.category_id=filters.category_id;if(filters.dates[0])params.date_from=filters.dates[0];if(filters.dates[1])params.date_to=filters.dates[1];const response=await api.get('/daily/transactions',{params});if(request===tableRequest.current){setRows(response.data.data||[]);setPagination(response.data.pagination);}}catch(error){if(request===tableRequest.current)message.error(apiMessage(error));}finally{if(request===tableRequest.current)setTableLoading(false);}},[period,filters]);
  useEffect(()=>{loadOverview();},[loadOverview]);
  useEffect(()=>{const timer=window.setTimeout(loadTransactions,filters.search?300:0);return()=>window.clearTimeout(timer);},[loadTransactions,filters.search]);
  useEffect(()=>()=>{overviewRequest.current+=1;tableRequest.current+=1;},[]);
  const refresh=async()=>{await Promise.all([loadOverview(),loadTransactions()]);};
  const submit=async action=>{if(saveInFlight.current)return;saveInFlight.current=true;setSaving(true);try{await action();message.success('Data Daily berhasil diperbarui.');setTopUpOpen(false);setAllocationOpen(false);setExpenseOpen(false);setExpenseCategoryId(null);setEditing(null);setBudgetCategory(null);await Promise.all([refresh(),refreshHeader?.()]);}catch(error){message.error(apiMessage(error));throw error;}finally{saveInFlight.current=false;setSaving(false);}};
  const categoryTotal=useMemo(()=>categories.reduce((sum,item)=>sum+safeNumber(item.spent_amount),0),[categories]);
  const emergency=overview?.emergency_fund;
  const deleteCategory=category=>submit(()=>api.delete(`/daily/categories/${category.id}`));
  return <div className="daily-page">
    <div data-daily-guide="header"><HeadNavbar title="Daily Expenses" icon={<CalendarOutlined/>} description="Kelola kebutuhan sehari-hari dan pantau pengeluaran bulanan bersama."/></div>
    <div className="daily-toolbar"><DatePicker picker="month" allowClear={false} value={month} onChange={value=>{if(value){setMonth(value.startOf('month'));setFilters(initialFilters);}}} format="MMMM YYYY"/><Space wrap><DailyGuidedTour ready={!loading&&!error} canManage={canManage}/>{canManage&&<Button data-daily-guide="topup" icon={<PlusOutlined/>} onClick={()=>setTopUpOpen(true)}>Isi Saldo Daily</Button>}{canManage&&<Button data-daily-guide="expense" type="primary" icon={<PlusOutlined/>} onClick={()=>{setEditing(null);setExpenseCategoryId(null);setExpenseOpen(true);}}>Tambah Pengeluaran</Button>}</Space></div>
    {error&&<Alert type="error" showIcon title="Daily belum dapat dimuat" description={error} action={<Button onClick={loadOverview}>Coba Lagi</Button>} style={{marginBottom:20}}/>}
    {loading?<Row gutter={[16,16]}>{summaryCards.map(([key])=><Col xs={24} sm={12} lg={8} key={key}><Card><Skeleton active paragraph={{rows:1}}/></Card></Col>)}</Row>:<Row gutter={[16,16]} className="daily-summary">{summaryCards.map(([key,label,icon])=><Col xs={24} sm={12} lg={8} key={key}><Card data-daily-guide={key==='balance'?'balance':undefined} className={`daily-summary-card daily-summary-card--${key}`}><span className="daily-summary-icon">{icon}</span><Statistic title={label} value={safeNumber(summary[key])} formatter={value=>rupiah(value)} suffix={key==='average_daily_spending'?<small>/ hari</small>:null}/>{key==='available_balance'&&canManage&&<Button data-daily-guide="allocate" className="daily-allocate-button" size="small" icon={<AppstoreAddOutlined/>} onClick={()=>setAllocationOpen(true)}>Bagi Saldo</Button>}</Card></Col>)}</Row>}
    {!loading&&!error&&safeNumber(summary.balance)===0&&categoryTotal===0&&<Alert className="daily-empty" type="info" showIcon title="Daily masih kosong" description={canManage?'Isi saldo Daily dan mulai catat kebutuhan bulanan agar pengeluaran lebih mudah dipantau.':'Belum ada saldo atau pengeluaran Daily yang dapat ditampilkan.'} action={canManage?<Button type="primary" onClick={()=>setTopUpOpen(true)}>Isi Saldo Daily</Button>:undefined}/>} 
    <section data-daily-guide="emergency" className="daily-section">{loading?<Card><Skeleton active/></Card>:emergency?<Card className="emergency-card"><Row gutter={[20,16]} align="middle"><Col xs={24} lg={9}><SafetyOutlined className="emergency-icon"/><Typography.Title level={3}>Dana Operasional Darurat Rumah 1 Tahun</Typography.Title><Typography.Text type="secondary">Dana cadangan untuk membantu menopang kebutuhan operasional rumah selama kondisi darurat.</Typography.Text></Col><Col xs={24} sm={8} lg={5}><Statistic title="Terkumpul" value={emergency.collected_amount} formatter={rupiah}/></Col><Col xs={24} sm={8} lg={5}><Statistic title="Target" value={emergency.target_amount} formatter={rupiah}/></Col><Col xs={24} sm={8} lg={5}><Statistic title="Kurang" value={emergency.remaining_amount} formatter={rupiah}/></Col><Col span={24}><Progress percent={Math.min(safeNumber(emergency.progress),100)} status="active" format={()=>`${safeNumber(emergency.progress).toFixed(1)}%`}/></Col></Row></Card>:<Card><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="Purpose Dana Operasional Darurat Rumah 1 Tahun belum ditemukan."/></Card>}</section>
    <section data-daily-guide="charts" className="daily-section"><div className="daily-section-heading"><div><h2>Analisis Pengeluaran</h2><p>Visual pengeluaran untuk {periodLabel}.</p></div></div><Row gutter={[16,16]}><Col xs={24} xl={10}><Card title="Pengeluaran Berdasarkan Kategori"><div className="daily-chart"><CategoryExpenseChart categories={categories}/></div></Card></Col><Col xs={24} xl={14}><Card title="Budget vs Pengeluaran"><div className="daily-chart"><BudgetActualChart categories={categories}/></div></Card></Col></Row></section>
    <section data-daily-guide="budgets" className="daily-section"><div className="daily-section-heading"><div><h2>Budget Kategori</h2><p>Alokasi dan pengeluaran dimulai dari Rp0 pada setiap bulan baru.</p></div></div>{loading?<Row gutter={[16,16]}>{Array.from({length:6},(_,i)=><Col span={24} key={i}><Card><Skeleton active/></Card></Col>)}</Row>:<Row gutter={[16,16]}>{categories.map(item=>{const status=budgetStatus(item.spent_amount,item.budget_amount);const actions=canManage?<Space size={0}><Button type="text" icon={<EditOutlined/>} onClick={()=>setBudgetCategory(item)}>Edit</Button><Popconfirm title={`Hapus kategori ${item.name}?`} description="Kategori akan dihapus dari halaman Daily. Riwayat transaksi lama tetap tersimpan." okText="Hapus Kategori" cancelText="Batal" okButtonProps={{danger:true}} onConfirm={()=>deleteCategory(item)}><Button danger type="text" icon={<DeleteOutlined/>}>Hapus</Button></Popconfirm></Space>:undefined;return <Col span={24} key={item.id}><Card className="daily-category-card" title={item.name} extra={actions}><div className="daily-category-stats"><div><span>Terisi</span><strong>{rupiah(item.budget_amount)}</strong></div><div><span>Terpakai</span><strong className="daily-category-used">{rupiah(item.spent_amount)}</strong></div><div><span>Sisa</span><strong>{rupiah(item.remaining_amount)}</strong></div></div><div className="daily-category-usage"><span><CalendarOutlined/> {item.last_expense_date?`Terakhir dipakai ${usageDate(item.last_expense_date)}`:'Belum ada pemakaian bulan ini'}{item.expense_count>0&&` · ${item.expense_count} transaksi`}</span>{canManage&&<Button type="primary" ghost icon={<CheckCircleOutlined/>} onClick={()=>{setEditing(null);setExpenseCategoryId(item.id);setExpenseOpen(true);}}>Catat Pemakaian</Button>}</div><div className="daily-category-meta"><Tag color={status.color}>{status.label}</Tag><span>{status.percentage.toFixed(0)}% terpakai</span></div><Progress percent={Math.min(status.percentage,100)} status={status.percentage>=100?'exception':'active'} showInfo={false}/></Card></Col>;})}</Row>}</section>
    <section className="daily-section"><Card title="Tren Pengeluaran 6 Bulan"><div className="daily-chart daily-chart--trend">{loading?<Skeleton active/>:<SpendingTrendChart trend={overview?.trend||[]} selectedMonth={periodKey}/>}</div></Card></section>
    <DailyTransactionTable rows={rows} loading={tableLoading} pagination={pagination} categories={categories} filters={filters} onFilters={setFilters} onPage={(page,page_size)=>setFilters(value=>({...value,page,page_size}))} onEdit={row=>{setExpenseCategoryId(null);setEditing(row);setExpenseOpen(true);}} onDelete={row=>submit(()=>api.delete(`/daily/expenses/${row.id}`))} canManage={canManage}/>
    {canManage&&<><DailyTopUpForm open={topUpOpen} saving={saving} onCancel={()=>setTopUpOpen(false)} onSubmit={values=>submit(()=>api.post('/daily/topups',values))}/>
    <DailyAllocationForm open={allocationOpen} saving={saving} categories={categories} period={periodLabel} balance={summary.balance} expenses={summary.expenses} onCancel={()=>setAllocationOpen(false)} onSubmit={values=>submit(()=>api.put('/daily/allocations',{...values,...period}))}/>
    <DailyExpenseForm open={expenseOpen} saving={saving} categories={categories} initial={editing} presetCategoryId={expenseCategoryId} onCancel={()=>{setExpenseOpen(false);setExpenseCategoryId(null);setEditing(null);}} onSubmit={values=>submit(()=>editing?api.put(`/daily/expenses/${editing.id}`,values):api.post('/daily/expenses',values))}/>
    <DailyBudgetForm category={budgetCategory} period={periodLabel} saving={saving} onCancel={()=>setBudgetCategory(null)} onSubmit={values=>submit(()=>api.put(`/daily/budgets/${budgetCategory.id}`,{...values,...period}))}/></>}
  </div>;
}
