export {default as Login} from './Login'
export {default as Dashboard} from './Dashboard'
export {default as History} from './History'
export {default as Investment} from './Investment'
export {default as Profile} from './Profile'
export {default as Agreement} from './Agreement'
export {default as Purpose} from './Purpose'